server:
  port: 8127
spring:
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - health
          - metrics
          - env